name: App CD - Deploy to ECS

on:
  push:
    branches:
      - develop
    paths:
      - 'app/**'
      - '.github/workflows/app-cd.yml'

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: nodejs-dev-ecs-cluster
  SERVICE_NAME: nodejs-dev-ecs-service
  TASK_FAMILY: nodejs-dev-ecs-task
  CONTAINER_NAME: nodejs-dev-app
  ECR_REPOSITORY: nodejs-dev-ecr

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::500849274222:role/nodejs-dev-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Get current task definition
        id: task-def
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query taskDefinition > task-def.json

      - name: Update container image
        run: |
          IMAGE_URI=500849274222.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$SHORT_SHA

          jq --arg IMAGE "$IMAGE_URI" '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            ) |
            .containerDefinitions[0].image = $IMAGE
          ' task-def.json > new-task-def.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json


      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment